// productData.js
export const initialProducts = [
  {
    id: 1,
    name: "Dharma",
    category: "Bio-Fertilizers",
    price: 450,
    stock: 25,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  
  {
    id: 3,
    name: "Bhishma",
    category: "Bio-Fertilizers",
    price: 899,
    stock: 5,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 4,
    name: "Karna",
    category: "Bio-Fertilizers",
    price: 280,
    stock: 30,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 5,
    name: "Arjun",
    category: "Bio-Fertilizers",
    price: 350,
    stock: 100,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 6,
    name: "Eklavya",
    category: "Bio-Fertilizers",
    price: 220,
    stock: 15,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 7,
    name: "Yadnya",
    category: "Bio-Fertilizers",
    price: 450,
    stock: 10,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 8,
    name: "Vajrastra",
    category: "Bio-Fungicides",
    price: 180,
    stock: 22,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 9,
    name: "Senapati",
    category: "Bio-Fungicides",
    price: 1200,
    stock: 5,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 10,
    name: "Shipaee",
    category: "Bio-Fungicides",
    price: 380,
    stock: 14,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 11,
    name: "Vijayanta",
    category: "Bio-Insecticides",
    price: 290,
    stock: 17,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 12,
    name: "Sardar",
    category: "Bio-Insecticides",
    price: 420,
    stock: 9,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 13,
    name: "Jawan",
    category: "Bio-Insecticides",
    price: 420,
    stock: 9,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  {
    id: 14,
    name: "Gada",
    category: "Bio-Nematicides",
    price: 420,
    stock: 9,
    Use: "Premium organic fertilizer for healthy plant growth",
    Benefits: "Premium organic fertilizer for healthy plant growth",
  },
  
];
